minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.228
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20
mod_id=betterdurability
mod_name=BetterDurabilityCommunity
mod_license=MIT
mod_version=1.21.1-1.3.8
mod_group_id=PinkCats.betterdurability
mod_authors=PinkCats
mod_description=A mod to prevent your precious tools from breaking
publish_version=beta
curseforge_id=1655072
modrinth_id=N7QL5MvX
bdc_publish_artifact_task_name=jar
bdc_publish_preparation_task_name=jar
bdc_publish_loader_id=neoforge
