modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT License"

[[mods]]
modId = "betterdurability"
version = "1.20.1-1.0.0"
displayName = "BetterDurabilityCommunity"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/better-durability-reforged"
logoFile = "betterdurability.png"
credits = "Thanks for this mod goes to Java and the Forge team."
authors = "Darkorg, TsXor"
description = '''A mod to prevent your precious tools from breaking.'''
