minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=betterdurability
mod_name=BetterDurabilityCommunity
mod_license=MIT
mod_version=1.20.1-1.0.0
mod_group_id=darkorg.betterdurability
mod_authors=Darkorg
mod_description=A mod to prevent your precious tools from breaking
